# Docker Compose Test Environment Configuration
# Usage: docker-compose -f docker-compose.test.yml up

services:
  # Note: Supabase is started by the CI workflow before Docker Compose
  # so we don't need a Supabase container here

  # Test Runner Service - Runs all tests in containers
  test-runner:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile.test
    container_name: aizen-test-runner
    environment:
      NODE_ENV: test
      CI: true
      # Use Supabase running on host (started by CI)
      SUPABASE_URL: http://host.docker.internal:54321
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      # Redis test connection
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ../../:/app
      - /app/node_modules
      - test-results:/app/test-results
      - coverage:/app/coverage
    command: npm run test:coverage
    networks:
      - aizen-network

  # Redis for test environment (isolated from dev)
  redis:
    image: redis:7.4-alpine
    container_name: aizen-redis-test
    ports:
      - "6380:6379" # Different port to avoid conflicts
    volumes:
      - redis-test-data:/data
    environment:
      # Test-specific Redis configuration
      REDIS_MAXMEMORY: 100mb
      REDIS_MAXMEMORY_POLICY: allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - aizen-network

  # API Gateway Test Configuration
  api-gateway:
    image: node:20-alpine
    container_name: aizen-api-gateway-test
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3100:3000" # Different port for test
    environment:
      NODE_ENV: test
      PORT: 3000
      # Use Supabase running on host (started by CI)
      SUPABASE_URL: http://host.docker.internal:54321
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres
      # Redis connection
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Test-specific settings
      LOG_LEVEL: error
      ENABLE_TEST_ENDPOINTS: true
      DISABLE_RATE_LIMITING: true
    command: npm run test
    networks:
      - aizen-network
    depends_on:
      redis:
        condition: service_healthy

  # Web Portal Test Configuration
  web-portal:
    image: node:20-alpine
    container_name: aizen-web-portal-test
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3101:3001" # Different port for test
    environment:
      NODE_ENV: test
      PORT: 3001
      NEXT_PUBLIC_API_URL: http://api-gateway:3000
      NEXT_PUBLIC_SUPABASE_URL: http://host.docker.internal:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      # Disable analytics in test
      NEXT_PUBLIC_DISABLE_ANALYTICS: true
    command: npm run test
    networks:
      - aizen-network
    depends_on:
      api-gateway:
        condition: service_started

  # Device Agent Test Configuration
  device-agent:
    image: node:20-alpine
    container_name: aizen-device-agent-test
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3102:3002" # Different port for test
    environment:
      NODE_ENV: test
      PORT: 3002
      API_GATEWAY_URL: http://api-gateway:3000
      DEVICE_ID: TEST-DEVICE-001
      # Faster intervals for testing
      HEARTBEAT_INTERVAL: 5000
      DIAGNOSTIC_INTERVAL: 10000
    command: npm run test
    networks:
      - aizen-network
    depends_on:
      api-gateway:
        condition: service_started

  # AI Orchestrator Test Configuration
  ai-orchestrator:
    image: node:20-alpine
    container_name: aizen-ai-orchestrator-test
    working_dir: /app
    volumes:
      - ../../:/app
      - /app/node_modules
    ports:
      - "3103:3003" # Different port for test
    environment:
      NODE_ENV: test
      PORT: 3003
      # Use mock AI responses in test
      ENABLE_AI_MOCK_MODE: true
      MOCK_RESPONSE_DELAY: 100
      # Disable external API calls
      CLAUDE_API_KEY: test-key-not-used
    command: npm run test
    networks:
      - aizen-network

  # Disable Redis Commander in test environment
  redis-commander:
    profiles:
      - never # Never run in test environment

networks:
  aizen-network:
    name: aizen-test-network

volumes:
  redis-test-data:
    name: aizen-redis-test-data
  test-results:
    name: aizen-test-results
  coverage:
    name: aizen-test-coverage
